## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Abu Dhabi,AE,24.47,54.37,95.00,71,98,4.70,overcast clouds
1,1,Lerici,IT,44.08,9.91,78.01,59,0,1.99,clear sky
2,2,Castro,BR,-24.79,-50.01,41.47,90,99,5.23,overcast clouds
3,3,Woodward,US,36.43,-99.39,86.00,35,40,11.41,scattered clouds
4,4,Tuy Hoa,VN,13.08,109.30,76.03,84,13,6.02,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
hotel_temp_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &  (city_data_df["Max Temp"] >= min_temp)]

In [6]:
# 4a. Determine if there are any empty rows.
hotel_temp_df.isnull().sum()

City_ID                0
City                   0
Country                1
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
hotel_df=hotel_temp_df.dropna()
hotel_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [8]:
hotel_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Lerici,IT,44.08,9.91,78.01,59,0,1.99,clear sky
3,3,Woodward,US,36.43,-99.39,86.00,35,40,11.41,scattered clouds
4,4,Tuy Hoa,VN,13.08,109.30,76.03,84,13,6.02,few clouds
6,6,Butaritari,KI,3.07,172.79,81.86,67,100,1.95,overcast clouds
7,7,Cayenne,GF,4.93,-52.33,86.00,62,90,11.41,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
561,561,Coahuayana,MX,18.73,-103.68,78.80,83,75,11.41,broken clouds
562,562,Mitchell,US,43.71,-98.03,89.60,52,1,10.29,clear sky
563,563,Pont-Saint-Esprit,FR,44.25,4.65,80.60,57,0,6.93,clear sky
566,566,Sabang,ID,5.89,95.32,83.03,70,72,4.74,broken clouds
567,567,Tucurui,BR,-3.77,-49.67,89.13,38,54,1.77,broken clouds

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.

hotel_df = hotel_temp_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Lerici,IT,78.01,clear sky,44.08,9.91,
3,Woodward,US,86.00,scattered clouds,36.43,-99.39,
4,Tuy Hoa,VN,76.03,few clouds,13.08,109.30,
6,Butaritari,KI,81.86,overcast clouds,3.07,172.79,
7,Cayenne,GF,86.00,overcast clouds,4.93,-52.33,
11,San Andres,CO,84.20,scattered clouds,12.58,-81.70,
12,Thunder Bay,CA,75.99,few clouds,48.40,-89.32,
14,Sao Filipe,CV,77.70,scattered clouds,14.90,-24.50,
15,Nouadhibou,MR,78.80,broken clouds,20.93,-17.03,
18,Ponta Do Sol,PT,73.99,light intensity drizzle,32.67,-17.10,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e.  Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   
    try:
        # Grab the first hotel from the results and store the name.
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):
        hotel_df.loc[index, "Hotel Name"]=np.nan  
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Lerici,IT,78.01,clear sky,44.08,9.91,Doria Park Hotel
3,Woodward,US,86.00,scattered clouds,36.43,-99.39,Holiday Inn Express & Suites Woodward Hwy 270
4,Tuy Hoa,VN,76.03,few clouds,13.08,109.30,CenDeluxe Hotel Tuy Hoa
6,Butaritari,KI,81.86,overcast clouds,3.07,172.79,Isles Sunset Lodge
7,Cayenne,GF,86.00,overcast clouds,4.93,-52.33,HÃ´tel Le Dronmi
...,...,...,...,...,...,...,...
561,Coahuayana,MX,78.80,broken clouds,18.73,-103.68,Hotel Los Arcos
562,Mitchell,US,89.60,clear sky,43.71,-98.03,Kelly Inn & Suites
563,Pont-Saint-Esprit,FR,80.60,clear sky,44.25,4.65,HÃ´tel de la Bourse
566,Sabang,ID,83.03,broken clouds,5.89,95.32,Hotel Citra
567,Tucurui,BR,89.13,broken clouds,-3.77,-49.67,BBB Rooms Centro Tucurui PA

In [12]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.isnull().sum()

City                    0
Country                 1
Max Temp                0
Current Description     0
Lat                     0
Lng                     0
Hotel Name             24
dtype: int64

In [13]:
clean_hotel_df=hotel_df.dropna()

In [14]:
clean_hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [15]:
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Lerici,IT,78.01,clear sky,44.08,9.91,Doria Park Hotel
3,Woodward,US,86.00,scattered clouds,36.43,-99.39,Holiday Inn Express & Suites Woodward Hwy 270
4,Tuy Hoa,VN,76.03,few clouds,13.08,109.30,CenDeluxe Hotel Tuy Hoa
6,Butaritari,KI,81.86,overcast clouds,3.07,172.79,Isles Sunset Lodge
7,Cayenne,GF,86.00,overcast clouds,4.93,-52.33,HÃ´tel Le Dronmi
...,...,...,...,...,...,...,...
561,Coahuayana,MX,78.80,broken clouds,18.73,-103.68,Hotel Los Arcos
562,Mitchell,US,89.60,clear sky,43.71,-98.03,Kelly Inn & Suites
563,Pont-Saint-Esprit,FR,80.60,clear sky,44.25,4.65,HÃ´tel de la Bourse
566,Sabang,ID,83.03,broken clouds,5.89,95.32,Hotel Citra
567,Tucurui,BR,89.13,broken clouds,-3.77,-49.67,BBB Rooms Centro Tucurui PA

In [16]:
# 8a. Create the output File (CSV)
output_data_file="../vacation_search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]
#Add a heatmap of temperature for the vacation spots and marker for each city.
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))